### PR TITLE
support modbus ascii mode

### LINKED ISSUE #81: Enhancement:  suport ascii mode
I am interested in adding ascii mode support for device-modbus-go. 

If it is helpful for our project. I am going to make a pull request. Thanks.

### PR DESCRIPTION
**Pull request by bretagne-peiqi**
Fix #81

### CODE REVIEW

**Comment by bretagne-peiqi** [comment]
@cloudxxx8  Hi, please help review, thanks.

**Comment by cloudxxx8** [comment]
sorry, we are busy on fuji release recently.  this feature will be targeting to the next release, geneva.
I will review the code after settle down fuji.  Do you know any simulator is easy to use for testing Modbus ascii?  Thanks.

**Comment by weichou1229** [comment]
@bretagne-peiqi 
Could you add more detail info to test the Modbus ascii?
Because this is a new feature, please provide the following information:
- how to set up a simulator
- set up a device profile
- create a device

**Comment by cloudxxx8** [comment]
close this PR due to no activity

**Pull request closed without merging**
