### PR TITLE
update to Go modules

### PR DESCRIPTION
**Pull request by ernestojeda**
Changes include:
 - remove glide references
 - update Dockerfile to go modules (remove glide and make prepare)
 - any reference of `DeviceObject` to `DeviceResource`
 - any reference of `github.com/edgexfoundry/edgex-go/pkg` to `github.com/edgexfoundry/go-mod-core-contracts`

Signed-off-by: Ernesto Ojeda <ernesto.ojeda@intel.com>

### CODE REVIEW

**Comment by ernestojeda** [comment]
@jamesrgregg @MightyNerdEric Can you add reviewers please.

**Comment by ernestojeda** [comment]
This ci-mangement PR will need to be merged before the checks will pass:

https://github.com/edgexfoundry/ci-management/pull/309

**Comment by ernestojeda** [comment]
Here is the verify job on the Jenkins sandbox verifying this commit sha `ca7adfde7438482f29781a239095138ff55f9561`:
https://jenkins.edgexfoundry.org/sandbox/job/device-modbus-go-master-verify-go/3/console

**Comment by dweomer** [comment]
Besides the seemingly spurious `hashicorp/go-rootcerts` issue with checksum mismatch, what is the reason we are not checking `go.sum`? It seems to be officially recommended: https://github.com/golang/go/wiki/Modules#should-i-commit-my-gosum-file-as-well-as-my-gomod-file

**Comment by ernestojeda** [comment]
> Besides the seemingly spurious `hashicorp/go-rootcerts` issue with checksum mismatch, what is the reason we are not committing `go.sum`? It seems to be officially recommended: https://github.com/golang/go/wiki/Modules#should-i-commit-my-gosum-file-as-well-as-my-gomod-file

I initially had issues with checking in the go.sum file when working on the device-sdk-go repository. The builds would fail on then Jenkins server due to checksum mismatches. So I started omitting the go.sum.  I had not seen this guidance as to why to check the file in. It makes total sense though. I will modify this PR to include the go.sum file. Thanks for the feedback @dweomer

**Comment by ernestojeda** [comment]
recheck

**Comment by ernestojeda** [comment]
@dweomer Yeah, I am getting the `hashicorp/go-rootcerts` checksum issue when committing the go.sum. I will leave it out for now until we figure out the underlying issue.

```
00:01:21.791 [0m[91mgo: downloading github.com/hashicorp/go-rootcerts v1.0.0
00:01:21.793 [0m[91mgo: verifying github.com/hashicorp/go-rootcerts@v1.0.0: checksum mismatch
00:01:21.820 	downloaded: h1:Rqb66Oo1X/eSV1x66xbDccZjhJigjg0+e82kpwzSwCI=
00:01:21.820 	go.sum:     h1:ueI78wUjYExhCvMLow4icJnayNNFRgy0d9EGs/a1T44=
00:01:21.820 [0m[91mmake: *** [Makefile:20: cmd/device-modbus] Error 1
00:01:21.823 [0mThe command '/bin/sh -c make build' returned a non-zero code: 2
```

**Comment by ernestojeda** [comment]
recheck

**Comment by ernestojeda** [comment]
recheck

**Comment by ernestojeda** [comment]
@MightyNerdEric Can you help get this merged please.

**Comment by jamesrgregg** [comment]
@SteveOss or @MightyNerdEric please take a look at this one.  I can't add reviewers to the PR.

**Comment by dweomer** [comment]
Follow-up note. This is due to how checksums are calculated in repositories with checksums, pre 1.11.4. See [golang/go/issues#29278](
https://github.com/golang/go/issues/29278#issuecomment-447537558)

**Pull request merged**
