### PR TITLE
feat: enable gosec and default linter set

### PR DESCRIPTION
**Pull request by jpwhitemn**
fixes:#320
Signed-off-by: jpwhitemn <jpwhite_mn@yahoo.com>

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-modbus-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) n/a
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) n/a
  <link to docs PR>

### CODE REVIEW

**Comment by bnevis-i** [comment]
Note: This PR is failing the semantic PR check.

**Comment by jpwhitemn** [comment]
recheck

**Comment by jpwhitemn** [comment]
can't seem to get the semantic checking to pass.  Closing this PR and reopening another.
@bnevis-i - I'll fix in the new PR

**Comment by bnevis-i** [comment]
> can't seem to get the semantic checking to pass. Closing this PR and reopening another. @bnevis-i - I'll fix in the new PR

On your local, do a git commit --amend  (with -s and/or -S) to fix the commit message, then git push

**Pull request closed without merging**
