### PR TITLE
feat: Remove Logging configuration

### PR DESCRIPTION
**Pull request by FelixTing**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Support logging has been removed so now the configuration is obsolete.

Issue Number: #204 

## What is the new behavior?
Removed the following sections from configuration.toml:
- [Logging]
- [Clients.Logging]

fix: #204 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

**Comment by lenny-intel** [comment]
Putting these PRs on hold/draft until after device services dot release is complete.

**Comment by FelixTing** [comment]
dot release 1.3.1 is complete, this PR is now ready for review. @lenny-intel could you please help take a look when you have time? thanks!

**Review by lenny-intel — APPROVED** [review]
LGTM

**Review by lenny-intel — APPROVED** [review]
LGTM

**Pull request merged**
